# Generated by Django 4.2.3 on 2023-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
