# Generated by Django 4.2.3 on 2023-08-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAdminApp', '0005_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantMenu',
            fields=[
                ('dishID', models.IntegerField(primary_key=True, serialize=False)),
                ('dishName', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='Yummy!!', max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'verbose_name': 'restuarantMenu',
            },
        ),
        migrations.DeleteModel(
            name='restuarantMenu',
        ),
        migrations.RenameField(
            model_name='dishcategory',
            old_name='categroyID',
            new_name='categoryID',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantAdminApp.dishcategory'),
        ),
    ]
