# Generated by Django 4.2.3 on 2023-08-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'dishCategory'},
        ),
        migrations.AlterModelOptions(
            name='restuarantmenu',
            options={'verbose_name': 'restuarantMenu'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'table'},
        ),
    ]
