# Generated by Django 4.2.3 on 2023-08-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAdminApp', '0002_alter_dishcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED'), ('occupied', 'OCCUPIED')], max_length=15),
        ),
    ]
