# Generated by Django 4.2.3 on 2023-08-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAdminApp', '0003_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarantmenu',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[(1, 'AVAILABLE'), (2, 'RESERVED'), (3, 'OCCUPIED')], max_length=15),
        ),
    ]
