# Generated by Django 4.2.3 on 2023-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAdminApp', '0004_restuarantmenu_description_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED'), ('occupied', 'OCCUPIED')], max_length=15),
        ),
    ]
