# Generated by Django 4.2.3 on 2023-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('customerID', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=20)),
                ('noOfMembers', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
