# Generated by Django 4.2.3 on 2023-08-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customers_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=20)),
                ('noOfMembers', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('tableID', models.IntegerField()),
                ('cartID', models.IntegerField()),
                ('entryTime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
