# Generated by Django 4.2.3 on 2023-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartID', models.IntegerField(primary_key=True, serialize=False)),
                ('dishes', models.CharField(max_length=20)),
                ('quantityOrdered', models.IntegerField()),
                ('totalAmountPerDish', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cartID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customerID',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tableID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
